global:
  domain: argocd.k8s.orb.local

configs:
  params:
    server.insecure: true

server:
  replicas: 1

  service:
    type: ClusterIP

  ingress:
    enabled: false

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

controller:
  replicas: 1

dex:
  enabled: false

redis-ha:
  enabled: false

redis:
  enabled: true

notifications:
  enabled: false
